
 SELECT * FROM promotions WHERE id < 1000 LIMIT 100              ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 50      ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 50                     ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 10                     ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 20            ;
 SELECT * FROM orders WHERE id > 0 LIMIT 100                     ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 5           ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 20             ;
 SELECT * FROM products WHERE id > 0 LIMIT 50                    ;
 SELECT * FROM products WHERE id > 0 LIMIT 200                   ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 200  ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 50             ;
 SELECT * FROM cart WHERE id > 0 LIMIT 50                        ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 20               ;
 SELECT * FROM offers WHERE id > 0 LIMIT 150                     ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 20         ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 100         ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 5      ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 150            ;
 SELECT * FROM admin WHERE id > 0 LIMIT 20                       ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 5                   ;
 SELECT * FROM products WHERE id < 1000 LIMIT 100                ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 20                   ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 10                  ;
 SELECT * FROM cart WHERE id > 0 LIMIT 150                       ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 5          ;
 SELECT * FROM admin WHERE id > 0 LIMIT 200                      ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 100                 ;
 SELECT * FROM products WHERE id > 0 LIMIT 100                   ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 200            ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 5                   ;
 SELECT * FROM admin WHERE id > 0 LIMIT 10                       ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 200                   ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 50                    ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 20       ;
 SELECT * FROM cart WHERE id > 0 LIMIT 20                        ;
 SELECT * FROM cart WHERE id > 0 LIMIT 5                         ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 50                     ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 100                 ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 5        ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 5               ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 100              ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 50                  ;
 SELECT * FROM products WHERE id < 1000 LIMIT 10                 ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 100            ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 200         ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 5       ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 200                 ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 100             ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 50                   ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 100               ;
 SELECT * FROM products WHERE id < 1000 LIMIT 50                 ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 150     ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 50         ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 5                 ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 10        ;
 SELECT * FROM products WHERE id < 1000 LIMIT 5                  ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 200           ;
 SELECT * FROM products WHERE id < 1000 LIMIT 150                ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 20          ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 150  ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 20                   ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 100                 ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 50               ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 10             ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 20                  ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 5                      ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 50        ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 100  ;
 SELECT * FROM offers WHERE id > 0 LIMIT 20                      ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 100             ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 20                    ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 200               ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 20      ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 20               ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 200                 ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 10      ;
 SELECT * FROM clients WHERE id > 0 LIMIT 5                      ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 150              ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 5                ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 10             ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 50                ;
 SELECT * FROM orders WHERE id > 0 LIMIT 10                      ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 10                  ;
 SELECT * FROM products WHERE id < 1000 LIMIT 200                ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 150               ;
 SELECT * FROM clients WHERE id > 0 LIMIT 100                    ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 100                  ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 50       ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 5                   ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 200            ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 150                  ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 50             ;
 SELECT * FROM orders WHERE id > 0 LIMIT 150                     ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 10              ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 20                     ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 50       ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 150                  ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 150      ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 50      ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 5                    ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 150           ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 5             ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 50     ;
 SELECT * FROM offers WHERE id > 0 LIMIT 5                       ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 100    ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 10       ;
 SELECT * FROM admin WHERE id > 0 LIMIT 100                      ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 5                    ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 150         ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 100      ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 200      ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 10                    ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 150            ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 200     ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 5              ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 10                ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 150        ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 20                  ;
 SELECT * FROM admin WHERE id > 0 LIMIT 5                        ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 5    ;
 SELECT * FROM cart WHERE id > 0 LIMIT 10                        ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 100                    ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 200             ;
 SELECT * FROM orders WHERE id > 0 LIMIT 20                      ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 200        ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 100            ;
 SELECT * FROM products WHERE id > 0 LIMIT 5                     ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 150      ;
 SELECT * FROM orders WHERE id > 0 LIMIT 50                      ;
 SELECT * FROM clients WHERE id > 0 LIMIT 200                    ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 5                      ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 20       ;
 SELECT * FROM offers WHERE id > 0 LIMIT 100                     ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 10          ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 20              ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 200     ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 100                   ;
 SELECT * FROM admin WHERE id > 0 LIMIT 50                       ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 100        ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 10                   ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 200                  ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 200                 ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 10                   ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 10            ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 200              ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 100      ;
 SELECT * FROM products WHERE id > 0 LIMIT 150                   ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 100       ;
 SELECT * FROM cart WHERE id > 0 LIMIT 100                       ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 10               ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 150              ;
 SELECT * FROM offers WHERE id > 0 LIMIT 10                      ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 10   ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 50                  ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 200              ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 200             ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 100     ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 150                    ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 20      ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 50              ;
 SELECT * FROM offers WHERE id > 0 LIMIT 50                      ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 100                    ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 5        ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 50          ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 200                    ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 200                  ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 150       ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 150                    ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 10       ;
 SELECT * FROM offers WHERE id > 0 LIMIT 200                     ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 150                   ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 100           ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 5         ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 10     ;
 SELECT * FROM orders WHERE id > 0 LIMIT 200                     ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 20   ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 200       ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 150     ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 10                     ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 100     ;
 SELECT * FROM products WHERE id > 0 LIMIT 20                    ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 150                 ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 50            ;
 SELECT * FROM clients WHERE id > 0 LIMIT 20                     ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 150             ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 150             ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 5       ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 100                  ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 50                  ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 10                  ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 50              ;
 SELECT * FROM clients WHERE id > 0 LIMIT 50                     ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 50               ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 5                ;
 SELECT * FROM products WHERE id < 1000 LIMIT 20                 ;
 SELECT * FROM products WHERE id > 0 LIMIT 10                    ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 20                     ;
 SELECT * FROM clients WHERE id > 0 LIMIT 150                    ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 20     ;
 SELECT * FROM cart WHERE id > 0 LIMIT 200                       ;
 SELECT * FROM orders WHERE id > 0 LIMIT 5                       ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 10               ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 20                ;
 SELECT * FROM admin WHERE id > 0 LIMIT 150                      ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 5                     ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 10              ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 5              ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 10         ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 200                    ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 50                   ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 5               ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 150    ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 10      ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 200    ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 20             ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 200      ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 50   ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 20              ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 150                 ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 20                  ;
 SELECT * FROM clients WHERE id > 0 LIMIT 10                     ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 20        ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 150                 ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 250               ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 250                    ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 250           ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 250                 ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 250  ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 250              ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 250              ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 250        ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 250                   ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 250             ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 250      ;
 SELECT * FROM offers WHERE id > 0 LIMIT 250                     ;
 SELECT * FROM products WHERE id < 1000 LIMIT 250                ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 250     ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 250                  ;
 SELECT * FROM admin WHERE id > 0 LIMIT 250                      ;
 SELECT * FROM clients WHERE id > 0 LIMIT 250                    ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 250         ;
 SELECT * FROM cart WHERE id > 0 LIMIT 250                       ;
 SELECT * FROM orders WHERE id > 0 LIMIT 250                     ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 250                    ;
 SELECT * FROM products WHERE id > 0 LIMIT 250                   ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 250            ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 250       ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 250                 ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 250                  ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 250                 ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 250     ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 250      ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 250    ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 250             ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 250            ;
 SELECT * FROM offers WHERE id > 0 LIMIT 450                     ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 450        ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 400      ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 300                  ;
 SELECT * FROM offers WHERE id > 0 LIMIT 500                     ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 350                 ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 450                 ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 300                 ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 400       ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 300             ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 500            ;
 SELECT * FROM orders WHERE id > 0 LIMIT 400                     ;
 SELECT * FROM cart WHERE id > 0 LIMIT 400                       ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 400            ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 400  ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 500         ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 400      ;
 SELECT * FROM cart WHERE id > 0 LIMIT 350                       ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 300                    ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 350            ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 350    ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 450                 ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 400                   ;
 SELECT * FROM admin WHERE id > 0 LIMIT 500                      ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 500     ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 450              ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 500              ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 350                    ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 500               ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 350                 ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 450                   ;
 SELECT * FROM cart WHERE id > 0 LIMIT 500                       ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 500                 ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 500       ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 300    ;
 SELECT * FROM admin WHERE id > 0 LIMIT 450                      ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 350            ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 300                 ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 400                 ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 300      ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 450            ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 300                  ;
 SELECT * FROM orders WHERE id > 0 LIMIT 350                     ;
 SELECT * FROM orders WHERE id > 0 LIMIT 500                     ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 500                 ;
 SELECT * FROM orders WHERE id > 0 LIMIT 300                     ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 350               ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 400                 ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 400                    ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 300              ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 350       ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 300              ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 450                    ;
 SELECT * FROM products WHERE id > 0 LIMIT 450                   ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 450                    ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 500             ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 450             ;
 SELECT * FROM products WHERE id < 1000 LIMIT 300                ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 450                  ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 450                  ;
 SELECT * FROM admin WHERE id > 0 LIMIT 300                      ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 350  ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 500                    ;
 SELECT * FROM products WHERE id < 1000 LIMIT 350                ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 350     ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 300                   ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 350        ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 350     ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 500    ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 400               ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 500                   ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 350                   ;
 SELECT * FROM clients WHERE id > 0 LIMIT 300                    ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 450            ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 400           ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 350              ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 400             ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 300         ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 500      ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 400            ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 300            ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 500            ;
 SELECT * FROM clients WHERE id > 0 LIMIT 500                    ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 300               ;
 SELECT * FROM offers WHERE id > 0 LIMIT 400                     ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 450      ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 300     ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 300     ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 300       ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 400                  ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 500        ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 450      ;
 SELECT * FROM products WHERE id > 0 LIMIT 350                   ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 450         ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 500             ;
 SELECT * FROM admin WHERE id > 0 LIMIT 400                      ;
 SELECT * FROM products WHERE id > 0 LIMIT 400                   ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 400                 ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 300            ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 450                 ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 450  ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 450               ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 350             ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 350         ;
 SELECT * FROM offers WHERE id > 0 LIMIT 300                     ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 500  ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 350              ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 400        ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 450             ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 450     ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 300           ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 350                    ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 300      ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 450    ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 450       ;
 SELECT * FROM products WHERE id > 0 LIMIT 500                   ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 500                  ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 500     ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 350             ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 350                  ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 450              ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 500              ;
 SELECT * FROM products WHERE id > 0 LIMIT 300                   ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 350                 ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 400     ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 400     ;
 SELECT * FROM products WHERE id < 1000 LIMIT 400                ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 500                  ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 300             ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 400                  ;
 SELECT * FROM cart WHERE id > 0 LIMIT 300                       ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 500                 ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 400              ;
 SELECT * FROM clients WHERE id > 0 LIMIT 450                    ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 400                    ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 450           ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 400         ;
 SELECT * FROM cart WHERE id > 0 LIMIT 450                       ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 400    ;
 SELECT * FROM products WHERE id < 1000 LIMIT 450                ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 350      ;
 SELECT * FROM clients WHERE id > 0 LIMIT 400                    ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 500                    ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 400              ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 350                  ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 300        ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 350      ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 300                    ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 500      ;
 SELECT * FROM clients WHERE id > 0 LIMIT 350                    ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 400             ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 300                 ;
 SELECT * FROM admin WHERE id > 0 LIMIT 350                      ;
 SELECT * FROM products WHERE id < 1000 LIMIT 500                ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 500           ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 350           ;
 SELECT * FROM orders WHERE id > 0 LIMIT 450                     ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 450     ;
 SELECT * FROM offers WHERE id > 0 LIMIT 350                     ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 300  ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 600                 ;
 SELECT * FROM admin WHERE id > 0 LIMIT 1000                     ;
 SELECT * FROM products WHERE id > 0 LIMIT 600                   ;
 SELECT * FROM cart WHERE id > 0 LIMIT 1000                      ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 800     ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 850    ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 550      ;
 SELECT * FROM admin WHERE id > 0 LIMIT 600                      ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 900             ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 750     ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 850                    ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 850               ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 550      ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 700                    ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 700            ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 1000    ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 800  ;
 SELECT * FROM clients WHERE id > 0 LIMIT 850                    ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 700      ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 900        ;
 SELECT * FROM products WHERE id < 1000 LIMIT 700                ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 800                 ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 750                   ;
 SELECT * FROM products WHERE id > 0 LIMIT 800                   ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 800                   ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 750              ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 550                    ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 700                 ;
 SELECT * FROM clients WHERE id > 0 LIMIT 750                    ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 750             ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 1000           ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 950                 ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 600                 ;
 SELECT * FROM clients WHERE id > 0 LIMIT 700                    ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 650                    ;
 SELECT * FROM clients WHERE id > 0 LIMIT 550                    ;
 SELECT * FROM offers WHERE id > 0 LIMIT 600                     ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 550                 ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 550              ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 850                 ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 900                 ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 700                  ;
 SELECT * FROM cart WHERE id > 0 LIMIT 800                       ;
 SELECT * FROM offers WHERE id > 0 LIMIT 550                     ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 800     ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 600           ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 550                   ;
 SELECT * FROM admin WHERE id > 0 LIMIT 950                      ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 950            ;
 SELECT * FROM clients WHERE id > 0 LIMIT 900                    ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 750             ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 850            ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 900      ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 850             ;
 SELECT * FROM admin WHERE id > 0 LIMIT 800                      ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 1000                ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 600    ;
 SELECT * FROM cart WHERE id > 0 LIMIT 750                       ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 950              ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 950                  ;
 SELECT * FROM cart WHERE id > 0 LIMIT 550                       ;
 SELECT * FROM products WHERE id < 1000 LIMIT 1000               ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 850           ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 650                 ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 850     ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 550     ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 750           ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 600     ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 1000       ;
 SELECT * FROM admin WHERE id > 0 LIMIT 550                      ;
 SELECT * FROM products WHERE id < 1000 LIMIT 750                ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 750                  ;
 SELECT * FROM products WHERE id > 0 LIMIT 850                   ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 700    ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 750  ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 700        ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 650     ;
 SELECT * FROM products WHERE id > 0 LIMIT 550                   ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 900              ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 550                 ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 1000            ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 750                 ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 700             ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 900                  ;
 SELECT * FROM offers WHERE id > 0 LIMIT 800                     ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 700         ;
 SELECT * FROM offers WHERE id > 0 LIMIT 950                     ;
 SELECT * FROM products WHERE id > 0 LIMIT 950                   ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 700      ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 750              ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 700                   ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 900            ;
 SELECT * FROM offers WHERE id > 0 LIMIT 900                     ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 550                  ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 700     ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 800                 ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 850              ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 750            ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 950      ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 700           ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 700              ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 800         ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 600                 ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 650              ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 950    ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 1000        ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 700       ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 900                   ;
 SELECT * FROM cart WHERE id > 0 LIMIT 700                       ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 950             ;
 SELECT * FROM products WHERE id > 0 LIMIT 900                   ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 600            ;
 SELECT * FROM orders WHERE id > 0 LIMIT 650                     ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 650                    ;
 SELECT * FROM admin WHERE id > 0 LIMIT 750                      ;
 SELECT * FROM cart WHERE id > 0 LIMIT 850                       ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 550              ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 1000              ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 600      ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 800        ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 650             ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 600              ;
 SELECT * FROM orders WHERE id > 0 LIMIT 900                     ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 600     ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 950           ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 650                 ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 900                 ;
 SELECT * FROM offers WHERE id > 0 LIMIT 650                     ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 650             ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 800                    ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 550            ;
 SELECT * FROM products WHERE id > 0 LIMIT 750                   ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 850            ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 550                 ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 850        ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 850                 ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 900               ;
 SELECT * FROM admin WHERE id > 0 LIMIT 850                      ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 650            ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 550               ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 650            ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 850                  ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 750         ;
 SELECT * FROM offers WHERE id > 0 LIMIT 1000                    ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 600              ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 700                  ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 650              ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 800       ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 850             ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 550                  ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 900     ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 550        ;
 SELECT * FROM products WHERE id > 0 LIMIT 1000                  ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 700             ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 750        ;
 SELECT * FROM orders WHERE id > 0 LIMIT 1000                    ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 550    ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 650    ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 600       ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 600                    ;
 SELECT * FROM cart WHERE id > 0 LIMIT 900                       ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 1000             ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 550       ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 1000                 ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 800                  ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 950       ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 850      ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 650     ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 900     ;
 SELECT * FROM orders WHERE id > 0 LIMIT 600                     ;
 SELECT * FROM clients WHERE id > 0 LIMIT 600                    ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 650      ;
 SELECT * FROM products WHERE id < 1000 LIMIT 850                ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 800              ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 800      ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 1000                  ;
 SELECT * FROM cart WHERE id > 0 LIMIT 950                       ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 600                   ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 800               ;
 SELECT * FROM admin WHERE id > 0 LIMIT 650                      ;
 SELECT * FROM cart WHERE id > 0 LIMIT 650                       ;
 SELECT * FROM products WHERE id < 1000 LIMIT 950                ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 950                 ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 900                    ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 800           ;
 SELECT * FROM admin WHERE id > 0 LIMIT 700                      ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 1000     ;
 SELECT * FROM orders WHERE id > 0 LIMIT 800                     ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 950              ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 550           ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 900       ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 1000   ;
 SELECT * FROM clients WHERE id > 0 LIMIT 1000                   ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 950               ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 950                    ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 750    ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 600        ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 600  ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 700                 ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 1000     ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 850              ;
 SELECT * FROM offers WHERE id > 0 LIMIT 750                     ;
 SELECT * FROM products WHERE id > 0 LIMIT 650                   ;
 SELECT * FROM orders WHERE id > 0 LIMIT 950                     ;
 SELECT * FROM orders WHERE id > 0 LIMIT 550                     ;
 SELECT * FROM cart WHERE id > 0 LIMIT 600                       ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 850       ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 900            ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 850                 ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 550  ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 600            ;
 SELECT * FROM offers WHERE id > 0 LIMIT 850                     ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 700              ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 650         ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 700     ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 800                  ;
 SELECT * FROM orders WHERE id > 0 LIMIT 750                     ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 600                  ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 550         ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 1000           ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 900                    ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 900  ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 800            ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 900    ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 600                  ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 750     ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 600                    ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 950             ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 750               ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 900              ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 950         ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 850                    ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 750       ;
 SELECT * FROM products WHERE id < 1000 LIMIT 550                ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 800              ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 750                    ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 1000 ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 850                   ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 850  ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 650        ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 900                 ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 1000             ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 750                 ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 650                  ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 850         ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 1000      ;
 SELECT * FROM orders WHERE id > 0 LIMIT 700                     ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 950                    ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 900           ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 600             ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 950        ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 800      ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 550            ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 600             ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 850                  ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 600               ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 1000                ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 750      ;
 SELECT * FROM products WHERE id < 1000 LIMIT 600                ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 650               ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 950                   ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 1000                   ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 1000                 ;
 SELECT * FROM products WHERE id < 1000 LIMIT 650                ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 650                 ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 950            ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 700            ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 800             ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 550     ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 600         ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 900         ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 950  ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 650                  ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 750                  ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 950     ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 750            ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 850      ;
 SELECT * FROM clients WHERE id > 0 LIMIT 800                    ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 900                  ;
 SELECT * FROM offers WHERE id > 0 LIMIT 700                     ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 950      ;
 SELECT * FROM clients WHERE id > 0 LIMIT 950                    ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 650       ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 800    ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 550             ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 800             ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 950     ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 800            ;
 SELECT * FROM orders WHERE id > 0 LIMIT 850                     ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 650      ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 1000                   ;
 SELECT * FROM products WHERE id < 1000 LIMIT 900                ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 800                    ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 700                 ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 750                    ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 700                    ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 650           ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 1000            ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 550                    ;
 SELECT * FROM clients WHERE id > 0 LIMIT 650                    ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 900             ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 650  ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 1000    ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 900      ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 850     ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 950                  ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 800                 ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 950                 ;
 SELECT * FROM admin WHERE id > 0 LIMIT 900                      ;
 SELECT * FROM products WHERE id < 1000 LIMIT 800                ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 750                 ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 600      ;
 SELECT * FROM products WHERE id > 0 LIMIT 700                   ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 1000          ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 700  ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 1000                ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 700               ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 650                   ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 550             ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 750      ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 1500                   ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 1500                  ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 1500                 ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 1500       ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 1500             ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 1500                ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 1500                ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 1500    ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 1500        ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 1500                ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 1500   ;
 SELECT * FROM products WHERE id > 0 LIMIT 1500                  ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 1500     ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 1500    ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 1500      ;
 SELECT * FROM cart WHERE id > 0 LIMIT 1500                      ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 1500           ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 1500 ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 1500     ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 1500           ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 1500            ;
 SELECT * FROM admin WHERE id > 0 LIMIT 1500                     ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 1500                 ;
 SELECT * FROM products WHERE id < 1000 LIMIT 1500               ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 1500             ;
 SELECT * FROM clients WHERE id > 0 LIMIT 1500                   ;
 SELECT * FROM products WHERE id > 0 LIMIT 2500                  ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 2500                ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 2500    ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 2500           ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 2500 ;
 SELECT * FROM cart WHERE id > 0 LIMIT 2500                      ;
 SELECT * FROM clients WHERE id > 0 LIMIT 2500                   ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 2500            ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 2500            ;
 SELECT * FROM products WHERE id < 1000 LIMIT 2500               ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 2500           ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 2500             ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 2500   ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 2500              ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 2500       ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 2500             ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 2500                 ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 2500    ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 2500                ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 2500        ;
 SELECT * FROM offers WHERE id > 0 LIMIT 2500                    ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 2500                   ;
 SELECT * FROM admin WHERE id > 0 LIMIT 2500                     ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 2500                 ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 2500          ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 5500           ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 5500            ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 5500             ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 5500       ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 5500   ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 5500        ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 5500                   ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 5500                 ;
 SELECT * FROM cart WHERE id < 1000 LIMIT 3000                   ;
 SELECT * FROM offers WHERE id IS NOT NULL LIMIT 3000            ;
 SELECT * FROM wilayas WHERE id > 0 LIMIT 3000                   ;
 SELECT * FROM orders WHERE id BETWEEN 10 AND 500 LIMIT 3000     ;
 SELECT * FROM orders WHERE id IS NOT NULL LIMIT 3000            ;
 SELECT * FROM clients WHERE id > 0 LIMIT 3000                   ;
 SELECT * FROM admin WHERE id > 0 LIMIT 3000                     ;
 SELECT * FROM products WHERE id BETWEEN 10 AND 500 LIMIT 3000   ;
 SELECT * FROM cart WHERE id BETWEEN 10 AND 500 LIMIT 3000       ;
 SELECT * FROM clients WHERE id BETWEEN 10 AND 500 LIMIT 3000    ;
 SELECT * FROM products WHERE id > 0 LIMIT 3000                  ;
 SELECT * FROM admin WHERE id BETWEEN 10 AND 500 LIMIT 3000      ;
 SELECT * FROM cart WHERE id IS NOT NULL LIMIT 3000              ;
 SELECT * FROM promotions WHERE id BETWEEN 10 AND 500 LIMIT 3000 ;
 SELECT * FROM admin WHERE id IS NOT NULL LIMIT 3000             ;
 SELECT * FROM clients WHERE id IS NOT NULL LIMIT 3000           ;
 SELECT * FROM offers WHERE id > 0 LIMIT 3000                    ;
 SELECT * FROM wilayas WHERE id BETWEEN 10 AND 500 LIMIT 3000    ;
 SELECT * FROM products WHERE id IS NOT NULL LIMIT 3000          ;
 SELECT * FROM promotions WHERE id < 1000 LIMIT 3000             ;
 SELECT * FROM orders WHERE id > 0 LIMIT 3000                    ;
 SELECT * FROM offers WHERE id < 1000 LIMIT 3000                 ;
 SELECT * FROM wilayas WHERE id IS NOT NULL LIMIT 3000           ;
 SELECT * FROM admin WHERE id < 1000 LIMIT 3000                  ;
 SELECT * FROM promotions WHERE id IS NOT NULL LIMIT 3000        ;
 SELECT * FROM wilayas WHERE id < 1000 LIMIT 3000                ;
 SELECT * FROM offers WHERE id BETWEEN 10 AND 500 LIMIT 3000     ;
 SELECT * FROM clients WHERE id < 1000 LIMIT 3000                ;
 SELECT * FROM promotions WHERE id > 0 LIMIT 3000                ;
 SELECT * FROM cart WHERE id > 0 LIMIT 3000                      ;
 SELECT * FROM orders WHERE id < 1000 LIMIT 3000                 ;
 SELECT * FROM products WHERE id < 1000 LIMIT 3000              ; 
 SELECT * FROM orders                     ;
 SELECT * FROM offers                  ;
 SELECT * FROM wilayas            ;
 SELECT * FROM admin                   ;
 SELECT * FROM promotions         ;
 SELECT * FROM clients                ;
 SELECT * FROM cart                    ;
 SELECT * FROM products            ; 